#!/bin/bash

SRCDIR=${1%"/"}/
SRCREP=${2}
PREFIX=${3}
DEPPREFIX=${4}
PRJS=$(find $SRCDIR -mindepth 1 -maxdepth 1 -type d)

for i in $PRJS; do
    PRJ=${i#$SRCDIR}
    if [ -e "$i/dep.mk" ]; then
        echo "OBJ_${PRJ} := ${PREFIX}${PRJ}"
        echo "DEP_${PRJ} := ${DEPPREFIX}${PRJ}"
        echo "${PREFIX}${PRJ}: ${DEPPREFIX}${PRJ}"
        echo ".PHONY: ${PRJ}"
        echo "${PRJ}: \${OBJ_${PRJ}}"
    fi
done

for i in $PRJS; do
    PRJ=${i#$SRCDIR}
    if [ -e "$i/dep.mk" ]; then
        echo "include ${SRCREP}/${PRJ}/dep.mk"
    fi
done
